---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sportsdata

<!-- badges: start -->
<!-- badges: end -->

A collection of exercise science datasets.

## Datasets

* `amstelgold`: Power data from three top ten finishers of the 2019 Amstel Gold cycling race.
* `bundesliga`: Results of all games of the first and second German Bundesliga. [(Source)](https://github.com/camminady/AllBundesligaGamesEver)
* `fifa21`: Statistics for all players in FIFA21. [(Source)](https://www.kaggle.com/bryanb/fifa-player-stats-database)
* `letour`: End results for all riders competing in the Tour de France. [(Source)](https://github.com/camminady/LeTourDataSet)
* `nflcombine`: Data from NFL combine and pro days since 1987. [(Source)](https://github.com/josedv82/public_sport_science_datasets)
* `olympics`: All athletes competing in the modern Olympic Games. [(Source)](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results)

Small datasets for teaching and learning:

* `goalkeepers`: Development of Spanish football goalkeepers according to their FIFA ratings.
* `gymnastics`: All gymnasts participating in the Rio 2016 Olympic Games.
* `rioathletics`: Competitors in three athletic disciplines of the Rio 2016 Olympic Games.
* `swimstars`: Data on some of the best swimmers in history.

## Installation

You can install the development version from [GitHub](https://github.com/smnnlt/sportsdata) with:

``` r
# install.packages("devtools")
devtools::install_github("smnnlt/sportsdata")
```



